#!/bin/sh
'''exec' "/Users/zaina/Documents/CS Projects/basis hackathon/sustainable fashion chat/fcvenv/bin/python3.10" "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from bin.rouge import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
